/* global L */

const P = {
  shinkolobwe: [-11.055, 26.547],
  staten: [40.6402778, -74.1419444],
  seneca: [42.716, -76.889],
  linde: [42.97441030070138, -78.8930735242712],
  electromet: [43.08744037093125, -79.00690488493662],
  hooker: [43.07958422985608, -79.00831731578447],
  loow: [43.2235, -78.9565],
  landfill: [43.091907120818256, -78.99969074065574],
  river: [43.0905, -79.062],
  region: [43.105, -78.925]
};

const nodes = [
  {
    id: "shinkolobwe", number: "1", role: "Extraction", date: "Before 1940",
    title: "Shinkolobwe mine", shortTitle: "Shinkolobwe",
    location: "Katanga, Belgian Congo — now the Democratic Republic of the Congo", point: P.shinkolobwe,
    received: "Uranium-bearing rock from one of the richest known deposits in the world.",
    process: "Workers mined extremely high-grade pitchblende. The ore entered an international supply chain controlled by Union Minière du Haut-Katanga.",
    outcomes: [{ kind: "material", destination: "African Metals Corporation warehouse, Staten Island", detail: "More than 1,000 tons were shipped across the Atlantic in steel drums and held near the Bayonne Bridge." }]
  },
  {
    id: "staten-island", number: "2", role: "Stockpiling", date: "1940–1942",
    title: "African Metals Corporation warehouse", shortTitle: "Staten Island",
    location: "2351 Richmond Terrace, Port Richmond, Staten Island", point: P.staten,
    received: "High-grade pitchblende shipped from Shinkolobwe in the Belgian Congo.",
    process: "The ore remained in 1,823 steel drums at the waterfront warehouse until the Manhattan Engineer District acquired its uranium content.",
    outcomes: [{ kind: "material", destination: "Seneca Ordnance Depot, Romulus", detail: "The Army loaded the drums onto Lehigh Valley Railroad lighters and sent them to Seneca for safekeeping on November 2, 1942." }]
  },
  {
    id: "seneca", number: "3", role: "Army custody", date: "November 1942",
    title: "Seneca Ordnance Depot", shortTitle: "Seneca Depot", location: "Romulus, New York", point: P.seneca,
    received: "The Staten Island stockpile of Congolese uranium ore.",
    process: "The Army placed the drums in secure wartime storage. This is the documented destination of the Staten Island stockpile.",
    outcomes: [{ kind: "context", destination: "Western New York’s uranium-processing network", detail: "The map next enters Linde, which processed African and American ores. The dotted line is a narrative connection, not a claim that every Staten Island drum went directly to Linde." }]
  },
  {
    id: "linde", number: "4", role: "Refining and waste", date: "Full-scale operation by July 1943",
    title: "Linde Air Products", shortTitle: "Linde", location: "Tonawanda, New York", point: P.linde,
    received: "African and American uranium ores entering the Manhattan Project supply network.",
    process: "Linde converted ore into black oxide, brown oxide, and uranium tetrafluoride—UF₄, known as “green salt.” Refining also left radioactive residues and contaminated materials.",
    outcomes: [
      { kind: "material", destination: "Electromet, Niagara Falls", detail: "Green salt moved onward for reduction into uranium metal." },
      { kind: "waste", destination: "LOOW / Niagara Falls Storage Site", detail: "Radioactive residues and contaminated materials entered the federal storage and disposal system." }
    ]
  },
  {
    id: "electromet", number: "5", role: "Reduction and waste", date: "Manhattan Project and Cold War",
    title: "Electromet", shortTitle: "Electromet", location: "Niagara Falls, New York", point: P.electromet,
    received: "Uranium tetrafluoride—green salt—from Linde.",
    process: "Electromet used magnesium to reduce UF₄ into uranium metal. The reaction also produced uranium-bearing C-2 slag and other radioactive waste.",
    outcomes: [
      { kind: "material", destination: "The wider federal production network", detail: "Uranium metal moved into fabrication, component production, and research." },
      { kind: "waste", destination: "Hooker Chemical", detail: "Uranium-bearing C-2 slag was sent for chemical recovery." },
      { kind: "waste", destination: "LOOW and the Union Carbide landfill", detail: "Other residues moved into federal and company disposal systems." }
    ]
  },
  {
    id: "hooker", number: "6", role: "Recovery and waste", date: "Wartime production",
    title: "Hooker Chemical", shortTitle: "Hooker", location: "Niagara Falls, New York", point: P.hooker,
    received: "Uranium-bearing C-2 slag generated by Electromet’s reduction process.",
    process: "Hooker treated the slag with hydrochloric acid to recover uranium. The recovery process produced another layer of solid and liquid residues.",
    outcomes: [
      { kind: "material", destination: "Linde", detail: "Recovered uranium-bearing material returned to the refining network." },
      { kind: "waste", destination: "Industrial drains, disposal systems, and waterways", detail: "Material that could not be recovered entered the region’s larger waste geography." }
    ]
  },
  {
    id: "loow", number: "7", role: "Federal storage and disposal", date: "1940s onward",
    title: "LOOW / Niagara Falls Storage Site", shortTitle: "LOOW / NFSS", location: "Lewiston, New York", point: P.loow,
    received: "Radioactive residues and contaminated materials from Linde, Electromet, and other federal work.",
    process: "The former Lake Ontario Ordnance Works became a place of storage, repackaging, transshipment, burial, and disposal. Material did not remain inside a single stable boundary.",
    outcomes: [
      { kind: "waste", destination: "Workers and private recipients", detail: "Accounts described gravel and fill leaving the reservation for destinations that were never completely recorded." },
      { kind: "waste", destination: "Roads, driveways, yards, businesses, and homes", detail: "Once reused, the material became part of the built environment." }
    ],
    caption: "Reuse labels describe categories—not mapped properties or hotspots."
  },
  {
    id: "uc-landfill", number: "8", role: "Company disposal and reuse", date: "Industrial operations",
    title: "Union Carbide company landfill", shortTitle: "Company landfill", location: "Niagara Falls Boulevard, Niagara Falls", point: P.landfill,
    received: "Industrial waste, slag, and contaminated material from Union Carbide’s Niagara Falls operation.",
    process: "The landfill was part of the company’s disposal chain. Trucking records also show waste and slag moving through private carriers and contractors.",
    outcomes: [
      { kind: "waste", destination: "Trucking companies and contractors", detail: "Once material entered private movement, its chain of custody became difficult to reconstruct." },
      { kind: "waste", destination: "Commercial sale and regional reuse", detail: "Untreated slag could be sold or used as inexpensive fill." }
    ],
    caption: "This map explains movement; it does not identify individual contaminated properties."
  },
  {
    id: "regional-reuse", number: "9", role: "Dispersal through reuse", date: "Destinations incompletely recorded",
    title: "The built environment", shortTitle: "Regional reuse", location: "Across Niagara and Erie Counties", point: P.region,
    received: "Slag, gravel, road bedding, and fill from workers, trucking companies, contractors, and industrial sites.",
    process: "Material was reused because it was available and inexpensive. Official records could follow only part of this dispersed, partly private network.",
    outcomes: [{ kind: "waste", destination: "Roads, parking lots, driveways, yards, businesses, and homes", detail: "The waste ceased to look like factory residue and became ordinary construction material beneath everyday places." }],
    caption: "The labels are reuse categories—not hotspots or individual addresses."
  },
  {
    id: "waterways", number: "10", role: "Liquid disposal", date: "Industrial operations",
    title: "Industrial drains and waterways", shortTitle: "Waterways", location: "Niagara Falls factory districts and the Niagara River", point: P.river,
    received: "Liquid, chemically contaminated, and radioactive waste from industrial processing and recovery.",
    process: "Liquid waste followed sewers, storm drains, and industrial waterways. Unlike barrels or slag, it left no neat boundary around a factory or dump.",
    outcomes: [{ kind: "waste", destination: "The Niagara River and connected waters", detail: "Water carried contamination through another route in the same industrial system." }]
  },
  {
    id: "wider-network", number: "11", role: "Fabrication and research", date: "Manhattan Project and Cold War",
    title: "The wider federal network", shortTitle: "Other factories", location: "Buffalo · Lackawanna · Lockport · Niagara Falls · Wheatfield", point: [43.02, -78.91],
    received: "Uranium metal, rods, components, and research materials moving through federal contracts.",
    process: "Bliss & Laughlin, Bethlehem Steel, Guterl, Carborundum, and Bell Aerospace participated in different stages of fabrication, testing, or weapons research.",
    outcomes: [{ kind: "context", destination: "Multiple production and waste histories", detail: "These sites are shown as one connected federal network—not as a single direct shipment chain. A direct route is drawn only where the evidence supports one." }]
  }
];

const markersData = nodes
  .filter(node => !["regional-reuse", "wider-network"].includes(node.id))
  .map(node => ({ id: node.id, nodeId: node.id, number: node.number, title: node.title, location: node.location, point: node.point }))
  .concat([
    { id: "bliss", nodeId: "wider-network", number: "11a", title: "Bliss & Laughlin Steel", location: "Buffalo, New York", point: [42.8407270474549, -78.8332865770902], secondary: true },
    { id: "bethlehem", nodeId: "wider-network", number: "11b", title: "Bethlehem Steel", location: "Lackawanna, New York", point: [42.82158, -78.85913], secondary: true },
    { id: "guterl", nodeId: "wider-network", number: "11c", title: "Guterl Specialty Steel", location: "Lockport, New York", point: [43.15669017990897, -78.71166549727371], secondary: true },
    { id: "carborundum", nodeId: "wider-network", number: "11d", title: "Carborundum", location: "Niagara Falls, New York", point: [43.08319964804595, -79.03875564160806], secondary: true },
    { id: "bell", nodeId: "wider-network", number: "11e", title: "Bell Aerospace", location: "Wheatfield, New York", point: [43.10091759197571, -78.93205624524674], secondary: true }
  ]);

const edges = [
  { id: "congo-staten", nodeIds: ["shinkolobwe", "staten-island"], kind: "material", path: [P.shinkolobwe, [-7.5,20], [-5.8,13.2], [4,-12], [24,-43], [38,-68], P.staten] },
  { id: "staten-seneca", nodeIds: ["staten-island", "seneca"], kind: "material", path: [P.staten, [41.15,-74.72], [42.05,-75.72], P.seneca] },
  { id: "seneca-linde", nodeIds: ["seneca", "linde"], kind: "context", path: [P.seneca, [42.87,-77.61], P.linde] },
  { id: "linde-electromet", nodeIds: ["linde", "electromet"], kind: "material", path: [P.linde, [43.021,-78.925], P.electromet] },
  { id: "electromet-hooker", nodeIds: ["electromet", "hooker"], kind: "waste", path: [P.electromet, [43.0838,-79.0115], P.hooker] },
  { id: "hooker-linde", nodeIds: ["hooker", "linde"], kind: "material", path: [P.hooker, [43.018,-78.972], P.linde] },
  { id: "linde-loow", nodeIds: ["linde", "loow"], kind: "waste", path: [P.linde, [43.106,-78.91], P.loow] },
  { id: "electromet-loow", nodeIds: ["electromet", "loow"], kind: "waste", path: [P.electromet, [43.151,-78.989], P.loow] },
  { id: "electromet-landfill", nodeIds: ["electromet", "uc-landfill"], kind: "waste", path: [P.electromet, [43.0902,-79.0037], P.landfill] },
  { id: "hooker-water", nodeIds: ["hooker", "waterways"], kind: "waste", path: [P.hooker, [43.082,-79.025], P.river] }
];

const nodeById = Object.fromEntries(nodes.map(node => [node.id, node]));
let activeId = null;

const map = L.map("map", {
  center: [20, -28], zoom: 2.4, minZoom: 2, maxZoom: 18, zoomControl: false, attributionControl: false
});
L.control.zoom({ position: "bottomright" }).addTo(map);

const satelliteLayer = L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}", { maxZoom: 18 });
const labelsLayer = L.tileLayer("https://{s}.basemaps.cartocdn.com/light_only_labels/{z}/{x}/{y}{r}.png", { subdomains: "abcd", maxZoom: 19, pane: "overlayPane" });
const streetLayer = L.tileLayer("https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png", { subdomains: "abcd", maxZoom: 19 });
satelliteLayer.addTo(map);
labelsLayer.addTo(map);

const routeLayer = L.layerGroup().addTo(map);
const markers = {};

markersData.forEach(data => {
  const icon = L.divIcon({
    className: `facility-marker-wrap${data.secondary ? " is-secondary-marker" : ""}`,
    html: `<span class="facility-marker" aria-hidden="true"><span>${data.number}</span><i></i></span>`,
    iconSize: data.secondary ? [38,52] : [42,58], iconAnchor: data.secondary ? [19,45] : [21,50]
  });
  const marker = L.marker(data.point, { icon, keyboard: true, title: `${data.title} — ${data.location}`, riseOnHover: true }).addTo(map);
  marker.bindTooltip(`<strong>${data.title}</strong><br><span>${data.location}</span>`, { direction: "top", offset: [0,-42], className: "facility-tooltip" });
  marker.on("click", () => selectNode(data.nodeId));
  markers[data.id] = marker;
});

function renderIndex() {
  const index = document.getElementById("network-index");
  nodes.forEach(node => {
    const button = document.createElement("button");
    button.type = "button";
    button.dataset.nodeId = node.id;
    button.innerHTML = `<span>${node.number}</span>${node.shortTitle}`;
    button.addEventListener("click", () => selectNode(node.id));
    index.appendChild(button);
  });
}

function routeColor(kind) {
  if (kind === "material") return "#440806";
  if (kind === "waste") return "#e8d9b6";
  return "#9d9d9d";
}

function routeDash(kind) {
  if (kind === "material") return null;
  return kind === "waste" ? "8 7" : "3 8";
}

function midpoint(path) {
  return path[Math.floor(path.length / 2)];
}

function bearing(path) {
  const middle = Math.max(0, Math.floor(path.length / 2) - 1);
  const start = path[middle];
  const end = path[middle + 1] || path[path.length - 1];
  return Math.atan2(end[0] - start[0], end[1] - start[1]) * (180 / Math.PI) * -1;
}

function drawNetwork() {
  routeLayer.clearLayers();
  edges.forEach(edge => {
    const isActive = activeId && edge.nodeIds.includes(activeId);
    L.polyline(edge.path, {
      color: routeColor(edge.kind),
      weight: isActive ? 4 : 1.7,
      opacity: isActive ? .98 : .42,
      dashArray: routeDash(edge.kind),
      className: `network-route-line${isActive ? " is-active-route" : ""}`
    }).addTo(routeLayer);

    if (isActive && edge.kind !== "context") {
      const icon = L.divIcon({
        className: `route-arrow-wrap is-${edge.kind}`,
        html: `<span class="route-arrow" style="transform:rotate(${bearing(edge.path)}deg)">➜</span>`,
        iconSize: [32,32], iconAnchor: [16,16]
      });
      L.marker(midpoint(edge.path), { icon, interactive: false }).addTo(routeLayer);
    }
  });

  markersData.forEach(data => {
    const marker = markers[data.id];
    const selected = data.nodeId === activeId;
    marker.setOpacity(activeId ? (selected ? 1 : .46) : .9);
    const element = marker.getElement();
    if (element) element.classList.toggle("is-active-marker", selected);
  });
}

function renderOutcomes(node) {
  const list = document.getElementById("outcome-list");
  list.replaceChildren();
  node.outcomes.forEach(outcome => {
    const section = document.createElement("section");
    section.className = `outcome is-${outcome.kind}`;
    const type = outcome.kind === "material" ? "Material" : outcome.kind === "waste" ? "Residue / waste" : "Connection";
    const label = document.createElement("span");
    label.textContent = type;
    const heading = document.createElement("h3");
    heading.textContent = outcome.destination;
    const detail = document.createElement("p");
    detail.textContent = outcome.detail;
    section.append(label, heading, detail);
    list.appendChild(section);
  });
}

function showOverlays(node) {
  document.getElementById("workers-overlay").hidden = node.id !== "loow";
  document.getElementById("haulers-overlay").hidden = node.id !== "uc-landfill";
  document.getElementById("reuse-overlay").hidden = node.id !== "regional-reuse";
  document.getElementById("water-overlay").hidden = node.id !== "waterways";
}

function moveMap(node) {
  if (node.id === "regional-reuse") {
    map.flyTo(P.region, 10.2, { duration: 1.2 });
    return;
  }
  if (node.id === "wider-network") {
    const points = markersData.filter(item => item.nodeId === "wider-network").map(item => item.point);
    map.flyToBounds(L.latLngBounds(points), { padding: [70,70], maxZoom: 10.2, duration: 1.2 });
    return;
  }
  const activeEdges = edges.filter(edge => edge.nodeIds.includes(node.id));
  const points = activeEdges.length ? activeEdges.flatMap(edge => edge.path) : [node.point];
  map.flyToBounds(L.latLngBounds(points), {
    padding: [76,76],
    maxZoom: ["electromet", "hooker", "uc-landfill", "waterways"].includes(node.id) ? 13 : 11,
    duration: 1.25
  });
}

function selectNode(id) {
  activeId = id;
  const node = nodeById[id];
  const activeIndex = nodes.findIndex(item => item.id === id);

  document.getElementById("discovery-card").hidden = true;
  document.getElementById("network-card").hidden = false;
  document.getElementById("node-kicker").textContent = `${node.number} · ${node.role}`;
  document.getElementById("node-date").textContent = node.date;
  document.getElementById("node-title").textContent = node.title;
  document.getElementById("node-location").textContent = node.location;
  document.getElementById("node-received").textContent = node.received;
  document.getElementById("node-process").textContent = node.process;
  document.getElementById("map-heading-title").textContent = node.shortTitle;
  document.getElementById("step-count").textContent = `${String(activeIndex + 1).padStart(2,"0")} / ${String(nodes.length).padStart(2,"0")}`;

  const next = document.getElementById("next-button");
  next.innerHTML = 'Next <span aria-hidden="true">→</span>';
  next.setAttribute("aria-label", "Next location");

  const caption = document.getElementById("network-caption");
  caption.hidden = !node.caption;
  caption.textContent = node.caption || "";
  document.getElementById("map-caption").textContent = node.caption || "Select another number to follow a different branch of the same system";

  document.querySelectorAll(".network-index button").forEach(button => {
    const selected = button.dataset.nodeId === id;
    button.classList.toggle("is-active", selected);
    if (selected) button.setAttribute("aria-current", "step");
    else button.removeAttribute("aria-current");
  });

  renderOutcomes(node);
  showOverlays(node);
  drawNetwork();
  moveMap(node);
}

document.getElementById("previous-button").addEventListener("click", () => {
  const current = activeId ? nodes.findIndex(node => node.id === activeId) : 0;
  selectNode(nodes[current <= 0 ? nodes.length - 1 : current - 1].id);
});

document.getElementById("next-button").addEventListener("click", () => {
  const current = activeId ? nodes.findIndex(node => node.id === activeId) : -1;
  selectNode(nodes[current < 0 || current === nodes.length - 1 ? 0 : current + 1].id);
});

document.getElementById("satellite-button").addEventListener("click", () => {
  if (map.hasLayer(streetLayer)) map.removeLayer(streetLayer);
  if (!map.hasLayer(satelliteLayer)) satelliteLayer.addTo(map);
  if (!map.hasLayer(labelsLayer)) labelsLayer.addTo(map);
  document.getElementById("satellite-button").classList.add("is-active");
  document.getElementById("map-button").classList.remove("is-active");
});

document.getElementById("map-button").addEventListener("click", () => {
  if (map.hasLayer(satelliteLayer)) map.removeLayer(satelliteLayer);
  if (map.hasLayer(labelsLayer)) map.removeLayer(labelsLayer);
  if (!map.hasLayer(streetLayer)) streetLayer.addTo(map);
  document.getElementById("map-button").classList.add("is-active");
  document.getElementById("satellite-button").classList.remove("is-active");
});

renderIndex();
drawNetwork();
window.setTimeout(() => map.invalidateSize(), 120);
