window.NIAGARA_PHOTOGRAPHS = [
  {
    "number": "01",
    "src": "https://drive.google.com/thumbnail?id=1UiUedeF9j365cxpT9GrTv2wREb7dhidS&sz=w2400",
    "title": "Rainbow Bridge and waterfalls from the Maid of the Mist. October 6th, 2023.",
    "caption": "The waterfalls of Niagara Falls hide a toxic and radioactive secret: the region’s role in the Manhattan Project and the nuclear buildup that followed left contamination on a scale comparable to Chernobyl. What draws tourists year after year—its waterfalls—also fueled the industries that caused its environmental decline and radioactive contamination. The “Honeymoon Capital of the World” has been the subject of numerous governmental studies, including radiological surveys, environmental assessments, and health investigations into its zip codes with clusters of cancers and endocrine disorders. These studies often fail to mention a crucial fact: for over 80 years, this area of western New York has been home to the highest concentration of radioactive landfills in the U.S. These perfectly manicured, bright green, and grassy landfills, disguised as strange-looking hills, are the toxic neighbors of quaint residential neighborhoods, public schools, and the Niagara River. The most alarming fact is that these studies often fail to mention the numerous radioactive hotspots scattered throughout the region. Unsurprisingly, cancer rates in Niagara are the highest in the U.S., a grim statistic that has remained unchanged for the past 40 years."
  },
  {
    "number": "02",
    "src": "https://drive.google.com/thumbnail?id=1DRyDRn-LagAS52jtt7Cqg7VmE13lvAKg&sz=w2400",
    "title": "Alex O’Malley by her old home on Ferry Avenue. October 6th, 2023.",
    "caption": "My journey into this project began with a troubling conversation with Alex O’Malley, a close friend and fourth-generation Niagara Falls native. “It’s polluted, very polluted,” she said. Over the past three years, my research has confirmed and reinforced her statement. Like many residents, O’Malley was unaware of Niagara Falls's involvement in the Manhattan Project and its lasting impact on the area. She and her two siblings suffer from hypothyroidism. According to the National Institute of Health, radiation exposure to the thyroid during childhood is a well-known environmental factor that can lead to hypothyroidism and other thyroid issues. The risk of developing these conditions increases with the dose of radiation and the age at exposure, with children exposed early in life being at the highest risk. She and her siblings attended Niagara Falls High School, now the Niagara Falls Cultural Center. In 1979, ORNL conducted an aerial radiological survey of Niagara County, revealing numerous radioactive areas. Seven years later, a more detailed mobile survey detected elevated gamma radiation at over 150 locations, ranging from 9 to 710 μR/h (U.S. background level ranges from 3 to 20 μR/h). The old high school revealed a reading of 23 μR/h. The O’Malley children grew up in a house on Ferry St., two blocks from another high gamma reading of uR/h 47. Portage Road, just a five-minute walk from their home, has 20 radioactive hotspots."
  },
  {
    "number": "03",
    "src": "https://drive.google.com/thumbnail?id=13DkJlhaAIOFngb7yK8SM2s6WKvkCP-lD&sz=w2400",
    "title": "Tourists at Niagara Falls Observation Deck. October 6th, 2023.",
    "caption": "In 2018, a contractor discovered radioactive waste at the entrance of Niagara Falls State Park, making headlines worldwide. It’s common practice to perform radiological surveys before breaking ground. Unbeknownst to many, including the residents of Niagara Falls, 80% of the uranium carried in Little Boy, the atomic bomb dropped on Hiroshima, was refined in local factories. In fact, Niagara Falls processed much of the uranium that fueled the Manhattan Project and the Cold War. This process generated massive amounts of radioactive waste in both liquid and solid forms. Government contractors disposed of the liquid waste into local waterways—creeks, rivers, and storm drains. The solid waste, a concrete-like radioactive material known as \"slag,\" piled up at unsupervised factory sites and at the Lake Ontario Ordnance Works, a military storage facility initially built in 1941 as a TNT plant. Unaware of its radioactive nature, workers often brought the slag home, using it as filler for home improvements such as paving driveways. Because this slag was free and abundant, construction and trucking companies began commercializing it and spreading it throughout the region. As a result, no structure in Niagara Falls built after the 1940s should be considered safe—not even the sidewalks."
  },
  {
    "number": "04",
    "src": "https://drive.google.com/thumbnail?id=1PxFJz0uwo9-kTmOyOvQMF_zIDqLyDUSO&sz=w2400",
    "title": "Carl Berak at Frankie’s Donuts. February 29th, 2024.",
    "caption": "In 1978, the working-class community of Love Canal became the focus of a major environmental disaster. The neighborhood got its name from a nearby man-made waterway owned by Hooker Chemical. Starting in the early 1940s, Hooker Chemical, along with other local industries and the military, had used the canal to dump toxic waste. Official records confirm this, and so do the stories from people who lived there. Carl Berak, a retired police officer, still meets friends daily at Frankie's Donuts Shop. He remembers driving EPA agents around Niagara Falls during the Love Canal disaster, and one of them seriously told him to leave the city for good."
  },
  {
    "number": "05",
    "src": "https://drive.google.com/thumbnail?id=14xCrZFHsMEUc_EF50EczpCq3ocXu9pGz&sz=w2400",
    "title": "Carl’s old police badge. February 29th, 2024.",
    "caption": ""
  },
  {
    "number": "06",
    "src": "https://drive.google.com/thumbnail?id=1XeoHKD7ZgOezIaEABI0oZFlEkliUvXu_&sz=w2400",
    "title": "Home, Love Canal, refused to relocate. October 8th, 2023.",
    "caption": "Standing atop the Love Canal chemical landfill, this home is one of the few remaining after the 1978 disaster. Approximately 200 families were relocated, and their homes and neighborhood demolished, but some residents refused to leave. Love Canal became the site of one of the worst environmental disasters in U.S. history and the catalyst for the federal Comprehensive Environmental Response, Compensation, and Liability Act (CERCLA)—better known as the Superfund program. This landmark legislation created the first major federal mechanism to hold polluters accountable and fund the cleanup of toxic waste sites across the nation."
  },
  {
    "number": "07",
    "src": "https://drive.google.com/thumbnail?id=1UyVfXKYfdXJaQ7frnfrCwQ4w6IGg4EEg&sz=w2400",
    "title": "Pump at Love Canal. March 2nd, 2024.",
    "caption": "An artificial barrier against Love Canal’s toxic legacy, this pump strains to hold back decades of contamination—sometimes working, sometimes not, according to those who live nearby. Despite knowing about the contamination, the city of Niagara Falls purchased the land from Hooker in 1953 to accommodate its growing baby boomer population. The chemicals buried in Love Canal leaked into residents' homes, leading to severe health issues, including leukemia, birth defects, and a significant rise in miscarriages. Lois Gibbs, organizer of the Love Canal Homeowners Association, brought public attention to the crisis in the late 1970s. Her activism forced the government to relocate 800 families and created the Comprehensive Environmental Response, Compensation, and Liability Act, known as Superfund."
  },
  {
    "number": "08",
    "src": "https://drive.google.com/thumbnail?id=1qfzngm9lcH46ZRWj84cwP4jeMOscZ9yh&sz=w2400",
    "title": "Lamppost, Love Canal. October 7th, 2023.",
    "caption": "All that remains of a once-lively neighborhood in Love Canal is a lone lamppost marking the site where families once lived—a haunting reminder of the toxic waste buried beneath. In the aftermath of the disaster, the New York State Assembly established a special task force to investigate residents’ claims of military personnel dumping waste into the old canal. Its damning 293-page Federal Connection Report revealed a web of ties between the U.S. Army, the Manhattan Engineering District (MED), and Niagara Falls’ chemical and metallurgical companies. Most alarming of all, the task force confirmed that the contamination was not only chemical—but radioactive."
  },
  {
    "number": "09",
    "src": "https://drive.google.com/thumbnail?id=1b6x8u3cftBHaK90frc_y7rfWEMr_QFnM&sz=w2400",
    "title": "Winter night, empty lot, Love Canal. January 24th, 2024.",
    "caption": ""
  },
  {
    "number": "10",
    "src": "https://drive.google.com/thumbnail?id=16Vf5l0qBw3kBj3iHoKkjtP-DEl7bmcuU&sz=w2400",
    "title": "Lewiston-Porter School. October 7th, 2023.",
    "caption": "Behind this school field lies the Lake Ontario Ordnance Works—today the Niagara Falls Storage Site (NFSS). At the end of World War II, the 7,500-acre LOOW was declared surplus, and by 1975 the War Assets Administration had sold off most of the land, leaving 191 acres that now make up the NFSS. The Lewiston-Porter School District purchased its parcel from the WAA in 1953 for just one dollar. Other sections were transferred to the National Guard Base, the Model Landfill, and CWM—a hazardous waste treatment and disposal facility. The school district borders the southwest drainage ditch from the former LOOW. Students regularly cross this ditch to reach running trails in nearby woods, where deer have been spotted with disturbing deformities. Testing of their livers revealed elevated levels of radium and cesium—radioactive elements linked to heart disease, lupus, leukemia, genetic disorders, and multiple cancers. In May 2011, the U.S. Army Corps of Engineers, which manages the NFSS, inspected the Lew-Port soccer field and recorded a Geiger counter reading of 57 μR/h. Unsurprisingly, this field had once been part of the Army’s radioactive storage site for the Manhattan Project. For more than five decades, community meetings have centered on the health and safety of residents living within a five-mile radius. A 2008 New York State Department of Health report, based on nine years of investigation, confirmed significantly elevated cancer rates in surrounding communities: excess cancers among males driven by high rates of prostate and testicular cancers; females showing elevated rates of breast and bladder cancers; and, most alarmingly, higher-than-expected cancer rates among children aged 10–14."
  },
  {
    "number": "11",
    "src": "https://drive.google.com/thumbnail?id=1pNv0i56V6cSjxyLheTsPgVmquOtX-mb2&sz=w2400",
    "title": "Chemical Waste Management Landfill. October 7th, 2023.",
    "caption": "Chemical Waste Management (CWM), a hazardous waste treatment, storage, and disposal facility, occupies surplus land from the former Lake Ontario Ordnance Works (LOOW). In 2005, when CWM sought to expand, a gamma walkover survey of the proposed landfill area identified numerous radioactive hotspots. An interior survey was also planned for six “legacy” buildings from LOOW’s 1940s operations, still in use by CWM personnel. Only one was actually assessed—and it was confirmed to be radioactive. From 1967 to 1970, while the new Lew-Port school was under construction, 279 students attended classes in three former Atomic Energy Commission nuclear fuel research buildings on the site. Just two years after the temporary campus closed, the property was fenced off due to high radiation levels. Many former students still wonder if their exposure contributed to the unusually high number of cancer cases among their peers."
  },
  {
    "number": "12",
    "src": "https://drive.google.com/thumbnail?id=1pEz8rYS09plHBQ4OiYs3Vm1wMNNGYdFA&sz=w2400",
    "title": "Home across from the former Lake Ontario Ordnance Works, now Niagara Falls Storage Site. October 7th, 2023.",
    "caption": "The Lake Ontario Ordnance Works (LOOW), set amid orchards and farmland, was camouflaged as a typical farm with barns and silos to avoid detection by enemy surveillance during World War II. Located less than a mile from the town of Lewiston, the Lew-Porter School, and five miles from the Niagara River, this radioactive storage site was shrouded in so much secrecy that it was ultimately forgotten. For forty-three years, highly radioactive waste languished in makeshift storage facilities at the LOOW site, including crumbling, uncovered concrete silos, deteriorating army structures, and open reservoirs where liquid waste was dumped, releasing dangerous levels of radioactivity into the environment. During a 1981 congressional hearing on “Uranium Ore Residues” John J. LaFalce, a representative of New York State, condemned the conditions at LOOW as shameful. In 1986, the Army Corps of Engineers consolidated the wastes and built the \"Interim Waste Containment Structure” (IWCS) to prevent further contamination. It's crucial to stress how \"interim\" this structure is. Designed with a lifespan of only 25-50 years, it consists of just six inches of compacted clay on top and lacks any protective liner at the bottom. Today, the site holds 67,500 cubic tons of radioactive waste, making it the world’s largest above-ground storage facility. By comparison, Chernobyl’s steel sarcophagus encloses 246 tons of radioactive waste."
  },
  {
    "number": "13",
    "src": "https://drive.google.com/thumbnail?id=1-7SSJd4mCAKEOlBLrCvXZQzYEiI4Rwwl&sz=w2400",
    "title": "Portrait of Kate O’Malley. October 6th, 2023.",
    "caption": "Kate O’Malley is the mother of Alex O’Malley and her two siblings, all of whom suffer from hypothyroidism. Like many other old-time residents, Ms. O'Malley's grandparents came from Ireland and Italy. Escaping poverty, they arrived in a city eager to lead the Industrial Revolution. Niagara’s early industrialization began in 1875 when the first hydroelectric mill began operating. Five years later, the construction of the 4,500-foot-long, 22-foot-wide Hydraulic Canal spurred the development of the city’s first industrial area, High Bank, located just north of the American Falls. In 1895, the Adams Power Station became the first industrial hydroelectric plant in the U.S. and the first to utilize Nikola Tesla’s Alternating Current (AC). Tesla’s innovation allowed electricity to travel farther from its source, enabling factories to move out of the polluted High Bank district and create two new industrial zones: Buffalo Avenue and the inland Highland district. Although vital to Niagara Falls' industrial expansion, these developments catalyzed the area's environmental decline and its citizens' health struggles."
  },
  {
    "number": "14",
    "src": "https://drive.google.com/thumbnail?id=1qeHbVF6wFj3fA2SopytN1S8gUbMFDHbn&sz=w2400",
    "title": "1930 Department of War Map of Niagara Falls, Niagara Falls Main Public Library. January 22nd, 2024.",
    "caption": "In 1942, Niagara Falls had a population of 72,000 and stood as one of the most prominent industrial cities in the United States, home to chemical factories and manufacturing plants—the black-marked areas on this map. Within these zones operated companies such as Hooker Chemical Co., Carborundum, and Union Carbide. Fueled by these industries, the city became a hub of innovation, comparable to today’s Silicon Valley. General Leslie Groves, head of the Manhattan Project, forged close ties with local factory owners, who pledged strict confidentiality in safeguarding sensitive operations. That secrecy came at a high cost: thousands of workers were unknowingly exposed to radioactive materials, a practice that extended well into the Cold War. It was not until 2000 that Congress acknowledged this hidden toll. With the passage of the Energy Employees Occupational Illness Compensation Program Act (EEOICPA), the government formally recognized that thousands of civilians and military personnel had been “inadvertently” exposed to radiation while serving the nation’s nuclear ambitions. This wall highlights the main culprits, but they were not alone: several additional companies in the area held contracts with the Manhattan Engineer District (MED), including Vanadium (Hooker), NL Industries, Globar Carborundum, and Bell Aerospace. Together, these industries embedded Niagara Falls into the hidden infrastructure of the Manhattan Project and Cold War nuclear production."
  },
  {
    "number": "15",
    "src": "https://drive.google.com/thumbnail?id=1oaLRcM3Je7ps2uWiYcodPql2jD-CeiD4&sz=w2400",
    "title": "Mount Cecos — Union Carbide Landfill. January 25th, 2024.",
    "caption": "An oddly, perfectly shaped mountain known locally as Mount Cecos rises beside Niagara Falls’ second most popular attraction, the Fashion Outlet Mall. The proximity is no coincidence: both the mall and Mount Cecos sit atop a former Union Carbide landfill. From 1942 to 1953, Union Carbide operated the nation’s largest ore-to-metal uranium production plant for the Manhattan Project, and government records show its radioactive work continued until 1965. The mall, built in 1982, was developed under the EPA’s Brownfield remediation program, which allows for lower standards of cleanup—sufficient for commercial redevelopment but not for residential use. Even so, environmental surveys connected to the mall’s expansion have consistently uncovered elevated levels of radiation. In 2014, soil excavated during construction triggered readings five times above background levels. That same area had once been home to the Sabre Park Mobile Home Community, where 280 families lived between 1976 and 2013. Today, Mount Cecos stands as a 385-acre toxic landfill—ten stories high and larger in scale than Niagara Falls itself. Buried within are the remains of the Carborundum factory, which conducted plutonium and uranium research under government contracts. Demolished in the 1990s but never properly decontaminated, its radioactive legacy remains entombed inside the landfill."
  },
  {
    "number": "16",
    "src": "https://drive.google.com/thumbnail?id=1d9Ty8qc5sNivy_e9Az_UfkwLBGBXAFdX&sz=w2400",
    "title": "Hooker S-Area Landfill. February 28th, 2024.",
    "caption": "Within the main Hooker Chemical (OxyChem) plant on Buffalo Avenue stood a secret facility code-named P-45, nicknamed the “bra factory” to confuse potential enemy spies because of a nearby Army plant that manufactured bras. Fenced off and guarded by military personnel, P-45’s primary purpose was to produce hexafluoroxylene, a liquid used in the gaseous diffusion process at Oak Ridge National Laboratory for the Manhattan Project. This process generated large amounts of hydrochloric acid waste, which was then used to strip the whitish oxide layer from uranium-bearing slag produced at Linde. The resulting sludge was stored in Hooker’s landfill within the main plant—later known as the S-Area landfill. In 1977, as part of the Formerly Utilized MED/AEC Remedial Program (FUSRAP), the Department of Energy conducted a radiological survey over 5.5 acres of the Hooker plant. Several buildings were found to be radioactive, including floors, furnaces, and other equipment used in uranium processing. Water samples from the adjacent Niagara River revealed concentrations of uranium, radium, and thorium—all exceeding health standards. Sludge samples from on-site manholes showed uranium concentrations of 6.2 pCi/g and 0.9 pCi/g—up to 2.5 times above acceptable limits. The Niagara River, into which these wastes drained, supplies drinking water to over one million people in the United States and Canada. The S-Area landfill, originally operated by Hooker Chemical—now Occidental—was later placed under the oversight of Glenn Springs Holdings, a subsidiary of Occidental. With its deceptively pastoral name, Glenn Springs assumed responsibility for the cleanup and long-term monitoring of several former Hooker sites, including both the S-Area landfill and Love Canal, as part of federal Superfund remediation efforts."
  },
  {
    "number": "17",
    "src": "https://drive.google.com/thumbnail?id=1O_Etk4MPjlwvADUW-VqY7Nye6eaMeRUd&sz=w2400",
    "title": "Linde’s radioactive train tracks. January 24th, 2024.",
    "caption": "Linde, a division of Union Carbide in Niagara Falls, was the first stop for uranium ore shipped from the Shinkolobwe mines in the Belgian Congo. The company already had expertise in refining uranium, as the element had long been used in small amounts as a ceramic and glass dye to produce vivid orange and green colors. Beginning in 1942, that expertise was redirected to the Manhattan Project, where Linde refined some of the richest uranium ore in the world. Because most industrial transport in the 1940s and 1950s was carried out by rail, uranium ore and radioactive byproducts moved in and out of the Linde site primarily along its rail lines. A 1998 survey by Oak Ridge National Laboratory identified 14 radioactive hotspots along the tracks at the site entrance (now Praxair), with readings ranging from 9 μR/h to 40 μR/h. From 1943 to 1953, Linde held contracts with the Manhattan Engineer District and later the Atomic Energy Commission to refine uranium ore into uranium tetrafluoride. Solid radioactive waste—though in smaller volumes—was shipped to the Lake Ontario Ordnance Works storage site. But according to the 1981 New York State Assembly Special Task Force on Love Canal, once Linde’s wells reached capacity, the Army Corps instructed the company to discharge liquid waste directly into its storm drains. In total, an estimated 37 million gallons of radioactive waste were released into the Niagara River. Today, Linde’s legacy is marked by multiple FUSRAP (Formerly Utilized Sites Remedial Action Program) locations in Tonawanda, where contaminated waste, soils, and buildings from the company’s Manhattan Project work remain under long-term cleanup by the U.S. Army Corps of Engineers. Tonawanda, with a population of roughly 75,000, has been the focus of health studies since the 1990s. A 2009 New York State Department of Health survey found significantly elevated cancer rates in census tracts surrounding the Tonawanda FUSRAP sites—most notably higher incidences of bladder, kidney, and lung cancers, as well as leukemia—raising ongoing concerns about the community’s continued exposure to Linde’s nuclear legacy."
  },
  {
    "number": "18",
    "src": "https://drive.google.com/thumbnail?id=15epnKpUU97WF8Qnu3BBJTu-lMD2yzNN8&sz=w2400",
    "title": "Electromet — Union Carbide Electro Metallurgical Company, Niagara Falls. February 28th, 2024.",
    "caption": "Electromet transformed the “green salts” refined at Linde into uranium metal, which was then shipped to Guterl Steel in Lockport and Bethlehem Steel in Buffalo to be converted into uranium rods. Uranium production at the Union Carbide Electro Metallurgical Company began in April 1943 and continued until August 1946, resuming briefly in October 1947. Today, empty lots and low-income homes occupy the eastern portion of the former Electromet plant, while another section of the site houses a Covanta waste incineration facility. An Environmental Impact Survey conducted in 2015 for Covanta reported: “Slag material exhibiting gamma radiation levels greater than two times the background level is intermingled with surface fill on the project site.” This slag, classified as TENORM (Technologically Enhanced Naturally Occurring Radioactive Material), has been found in several hotspots, especially in the northern portion of the property. Despite this history, no radiological survey has ever been conducted in the residential areas now covering part of the former Electromet grounds. Union Carbide (UCC) is today a subsidiary of The Dow Chemical Company."
  },
  {
    "number": "19",
    "src": "https://drive.google.com/thumbnail?id=1Mu3N7mAToDdj0E0bP546uNgrIvewmDsv&sz=w2400",
    "title": "Diorama, Maid of the Mist and the waterfalls, Niagara Falls Main Public Library. January 22nd, 2024.",
    "caption": "The name Maid of the Mist stems from a Seneca legend about a young woman, Lelawala, who was saved by the thunder god Heno after falling into Niagara Falls. Unlike the mythical rescue of Lelawala, the idea of rescuing Niagara Falls and restoring it to the fertile land once inhabited by the Senecas is a fallacy. Because of the radioactive nature of the contamination, complete decontamination is impossible. Most of the uranium ore refined in Niagara came from the Shinkolobwe mines in the Belgian Congo, whose deposits contained up to 7,000 times more uranium than ore mined in the United States. This extraordinarily high radioactivity made Congolese uranium a crucial component in the Manhattan Project. The radioactive slag it produced—unknowingly carried home by factory workers and distributed by construction and trucking companies—became a hidden byproduct of this high-yield uranium, embedding contamination into daily life across the region."
  },
  {
    "number": "20",
    "src": "https://drive.google.com/thumbnail?id=1tD4sjqE-NOhZ8ka_BInjluPZnffmnx8j&sz=w2400",
    "title": "Niagara Falls Community Missions Emergency Housing Shelter on the former grounds of Carborundum. October 8th, 2023.",
    "caption": "The 1986 Oak Ridge National Laboratory radiological survey recorded gamma readings of 120 μR/h on the site. From 1943 to 1944, Carborundum developed methods for shaping uranium rods, including forming, coating, and canning them for the MED. Between 1959 and 1967, the company produced uranium and plutonium carbide pellets and engaged in nuclear fuel development for the AEC. Founded in 1891, the Carborundum Company was once a pillar of Niagara’s industrial identity. It ceased operations in 1983, marking the end of an era. The Buffalo Avenue plant was demolished in 1993, but the areas involved in nuclear activities were never decontaminated. The radioactive rubble from the site was instead buried in the nearby Cecos landfill—adding to Niagara’s long shadow of contamination."
  },
  {
    "number": "21",
    "src": "https://drive.google.com/thumbnail?id=1V3K63CSiMB3q9RfTWHc7jXS4iIA46-yP&sz=w2400",
    "title": "The waterfalls. October 6th, 2023.",
    "caption": "Because the Niagara River supplies drinking water to more than a million people in both the U.S. and Canada, its contamination has long been a matter of international concern. In the late 1970s and 1980s, the International Joint Commission (IJC)—a bi-national body created under the Boundary Waters Treaty—surveyed the river and confirmed the presence of uranium, evidence that radioactive residues from wartime and Cold War production had spread into this vital waterway. Local surveys reinforced these findings. In 1977, as part of the Formerly Utilized MED/AEC Remedial Action Program, Hooker Chemical’s S-Area landfill was investigated. Water samples from the Niagara River, adjacent to the landfill, contained uranium, radium, and thorium at concentrations exceeding health standards. Around the same time, the New York State Department of Environmental Conservation (DEC) surveyed creeks in the area and found uranium contamination in Cayuga Creek, a tributary that flows directly into the Niagara River. Together, these surveys—international, federal, and state—exposed how poorly controlled radioactive waste disposal at sites like Linde, Hooker, and LOOW had not only poisoned local soils but infiltrated creeks and rivers, embedding the nuclear legacy directly into the region’s waterways."
  },
  {
    "number": "22",
    "src": "https://drive.google.com/thumbnail?id=1HfQf0clBX_0ticOpSD2IpOK7qBQZ40u5&sz=w2400",
    "title": "Suicide and Crisis Hotline telephone booth by the entrance of Niagara Falls State Park. October 6th, 2023.",
    "caption": "Radioactive gravel was discovered in soil at Niagara Falls State Park during a 2018 construction project, and on July 22, 2025, additional radioactive slag was uncovered. Health data from 2016–2018 shows that Niagara County had one of the highest suicide death rates in New York State, while heart disease remains the leading cause of death, followed by cancer. Studies conducted in the aftermath of Chernobyl, Hiroshima, and Nagasaki have demonstrated clear links between ionizing radiation and increased rates of cancer, cardiovascular disease, and endocrine disorders. Uranium-235, present in the slag used as filler material across the region and stored in unlined landfills, emits ionizing radiation through both gamma rays and alpha particles. Gamma radiation—widespread in Niagara Falls due to this waste—penetrates the body and damages internal organs, heightening the risk of cancers, cardiovascular disease, reproductive problems, thyroid dysfunction, and mental health disorders. For tourists, a brief drive through these hotspots poses minimal risk compared to the long-term exposure faced by residents. Radiation exposure is cumulative—repeated or prolonged contact carries far greater risks than short encounters—and no dose is considered entirely safe. This is why the radiation safety standard known as the “ALARA” principle (“as low as reasonably achievable”) remains the benchmark for minimizing harm."
  },
  {
    "number": "23",
    "src": "https://drive.google.com/thumbnail?id=1wq22_lwmlSzDM_gNJ6FfTkG9ocYTXBWf&sz=w2400",
    "title": "Niagara Falls High School, now Niagara Falls Cultural Center. March 1st, 2024.",
    "caption": "In a letter dated December 16, 1945, to the president of Union Carbide, General Leslie Groves—head of the Manhattan Project—expressed deep gratitude for the company’s critical role in developing the atomic bomb, which he credited with saving countless American lives. Groves noted the significance of the moment, writing that, for the first time in five years, Americans could celebrate Christmas without the shadow of war. Yet the bomb not only killed, poisoned, and upended the lives of 200,000 civilians in Japan—it also left a dark legacy in Niagara. Generations of residents have been exposed to both low and high levels of ionizing radiation from the industries that supported the Manhattan Project. The old Niagara Falls High School, with a gamma reading of 23 μR/h, served around 430 students annually until its closure in 2000—meaning an estimated 34,000 students were exposed to radiation since 1940."
  },
  {
    "number": "24",
    "src": "https://drive.google.com/thumbnail?id=1-Pdwq29UjcPc8cYYgYnUYpQJo2_GEprs&sz=w2400",
    "title": "Niagara Falls Aquarium. February 29th, 2024.",
    "caption": "The Aquarium of Niagara in Niagara Falls, New York, opened to the public on June 12, 1965, and has long served as a hub for education, where children of all ages come to learn about marine life. Yet in 2015, a radiological survey along the Robert Moses Parkway revealed alarming readings—exceeding 80 µR/h—near both the Aquarium and the Park Police station, raising concerns about the safety of a place that welcomes countless families and school groups."
  },
  {
    "number": "25",
    "src": "https://drive.google.com/thumbnail?id=1dz5V4y-JdRost7WvuIpeni5MvhWiAiBD&sz=w2400",
    "title": "Dead tree on Portage Road. October 6th, 2023.",
    "caption": "The 1986 Oak Ridge National Laboratory (ORNL) radiological survey identified twenty radioactive hotspots along Portage Road, spanning five consecutive blocks, with readings ranging from 17 μR/h to 91 μR/h. Radiation exposure disrupts tree growth by damaging cell division and weakening root and vascular systems. Over time, this leads to crown dieback, barren branches, and premature death—as seen here in Niagara, where decades of radioactive waste continue to scar the environment. No other street in the United States is as radioactive as Portage Road, and no other area in the country contains such a dense concentration of factories and landfills requiring remediation from radioactive contamination. To fully grasp the extent of this issue in Niagara Falls, one must understand the distribution of the forty-six contaminated sites managed under the Formerly Utilized Sites Remedial Action Program (FUSRAP), a Department of Energy initiative created to clean up radiation left behind by factories involved in the Manhattan Project. Of these sites, eight are located in Tennessee, two in Washington, ten in New Mexico, four in Nevada, and thirty-six in New York State—thirteen of which are concentrated in Niagara Falls alone. Until 2000, the DOE oversaw FUSRAP, making little progress in decontaminating the region. In a grim irony, Congress transferred authority to the U.S. Army Corps of Engineers—the same agency that once led the Manhattan Project. Yet it is crucial to note that the term remedial in FUSRAP, or in any government cleanup program, does not mean these factories or landfills are now safe. Instead, it means radiation has been contained and is continuously monitored, under the same “stringent” standards applied to Superfund sites—standards that still leave residents living alongside contamination."
  },
  {
    "number": "26",
    "src": "https://drive.google.com/thumbnail?id=1Tqs04MEitujvCKloo5dKTffKYE3mIVlS&sz=w2400",
    "title": "The chimneys of the old Globar (Carborundum) rise behind Potters Field Nursery playground. March 3rd, 2024.",
    "caption": "The Globar Plant, once operated by Carborundum in the Highland Industrial District, shut down in 1980 and is now listed under the EPA’s Brownfield Program. Brownfields are abandoned or underutilized industrial lands contaminated by hazardous waste. This particular site is heavily radioactive: a 2013 radiological survey identified as many as twenty hotspots, with readings ranging from 300 cpm to 60,000 cpm. (For comparison, radiation levels at Fukushima reached 100,000 cpm.) Across the Highland District, many contaminated post-industrial Brownfield sites remain undeveloped because cleanup costs exceed the land’s market value. Yet the EPA offers corporations financial incentives to redevelop these areas for low-residency structures such as hotels and malls—while residents, earning a per capita income of just $27,325 as of 2021, receive no comparable support. Trapped by limited social mobility, many are left with no choice but to live amid contamination. Closer to Niagara Falls itself, Brownfield incentives have fueled a new wave of development on parcels where environmental surveys once measured radiation as high as 309 μR/h. Although these lands are now designated “remediated” to meet Brownfield standards, the cleanup falls far short of what could be considered complete or safe. By law, Brownfield sites must conduct Environmental Impact Surveys, which are publicly available online. Each survey includes a radiological assessment—or “rad survey”—and the evidence presented here is drawn directly from those reports."
  },
  {
    "number": "27",
    "src": "https://drive.google.com/thumbnail?id=17i3t4jFMqg7EPtgsNSUVCMIrJ3fOzfKL&sz=w2400",
    "title": "Former Niagara Falls Airport, now Aerospace Museum, shared grounds and runway with Bell Aircraft. March 3rd, 2024.",
    "caption": "The 1979 ORNL Aerial Radiological Survey of Niagara Falls found elevated exposure rates near Pine Avenue, close to Niagara Falls International Airport. While the survey did not name specific sites, this area housed the Bell Aircraft Company, which in 1950 developed the first supersonic nuclear missile, the RASCAL (RAdar SCAnning Link). Equipped with an advanced guidance system, the RASCAL could deliver a 5,000-pound nuclear warhead. By comparison, the uranium-235 bomb dropped on Hiroshima, Little Boy, weighed about 9,700 pounds. Founded in Buffalo in 1935, Bell moved its main operations to Niagara Falls in 1940. The company produced Cobra planes during World War II and Iroquois helicopters during the Vietnam War. Bell’s innovations in jet propulsion reshaped aviation: in 1943, it built the first U.S. jet aircraft, and its experimental X-1 became the first plane to break the sound barrier in the 1950s—achievements that later paved the way for NASA’s space program. Historical Sanborn maps from 1932 to 1950 confirm the presence of a Carborundum facility within Bell’s factory grounds, alongside a larger Carborundum plant nearby. From 1943 to 1967, Carborundum conducted extensive nuclear research under government contracts, including plutonium experiments and nuclear fuel development."
  },
  {
    "number": "28",
    "src": "https://drive.google.com/thumbnail?id=1uevMHXL3OsFDNmrJ4emNZQWu1tlk0Ewu&sz=w2400",
    "title": "Holy Family Parish, Niagara Falls. October 6th, 2023.",
    "caption": "Once part of a vibrant Italian neighborhood, St. Joseph has seen its parishioners dwindle. By the 1960s, Niagara Falls's industrial golden age was dimming, mirrored by its dwindling population. The evolution of the shipping industry diminished the strategic advantage of its riverside location. Age-old companies, seeking cheaper labor, shifted operations overseas. As a result, the only remaining job opportunities were in the hospitality and nursing home sectors. Given the nature of these minimum-wage positions, they were less appealing than the good old factory jobs, leading to a mass exodus from the area. This catalyzed a mass departure, plummeting the city's population from 102,394 in 1960 to 48,671 by 2020. Those who stayed often found work in factories like Praxair (formerly Union Carbide) and OxyChem (formerly Hooker), where the dangers were well-known among locals. Multiple generations worked side by side, exposed to carcinogenic chemicals and asbestos on the factory floor. Like many other factories involved in the atomic bomb, the floors, furnaces, walls, and beams where uranium was once stored and refined were never decontaminated, exposing thousands more workers to “residual radiation.”"
  }
];
